neicnordic/sda-doa

Dockerfile, hooks/build
This PR aims at automating the building and pushing of images of the ega-doa outgestion component.
=> Dockerhub automated building

Dockerfile, src/main/resources/application.yml
1) Add public CA root
2) Rename ENVs for clarity
3) Change some defaults to reflect a non dev environment
Fixes: #6
=> S3 updates

src/main/java/no/uio/ifi/localega/doa/rest/StreamingController.java, src/main/resources/application.yml
This needs to be added in order for the posix file path to point to the right place in the archive
@jbygdell - might need an envar in helm charts
=> add archivepath for posix file systems

pom.xml
bump version to 1.4.0
Missing javax dependency added according to: https://github.com/spring-projects/spring-boot/issues/21465
=> Update spring boot

.github/workflows/publish.yml
This will bump the patch number on each PR merge unless the commit message contains **&#35;none**. 
In order to bump the major or minor version add **&#35;major** or **&#35;minor** to the PR message.
**&#35;major** -> v1.2.3 > 2.0.0
**&#35;minor** -> v1.2.3 > 1.3.0
If a new tag is created the second part of the action will build an docker image and publish it to the GithHub Container Registry.
The new image can the be pulled by calling `docker pull ghcr.io/neicnordic/sda-doa:latest`
1. Action to automatically bump the tag on push to master or PR merge.
2. Builds new Docker image and published to GHCR when tag changes.
3. pushes to docker hub as well
#none Do not bump the version for this PR
@jbygdell who did the original code for this
=> publish image on new tag

.github/workflows/test.yml
Change `settings.xml` location
=> Fix settings.xml location

.github/workflows/trivy.yml
Use Trivy to scan the latest container for security issues
=> Scan latest published container daily

.github/dependabot.yml
Added uio-bmi and elixir-oslo organisations to dependabot to pull in updates for repositories hosted in those orgs
=> added maven github repos

pom.xml, src/main/java/no/uio/ifi/localega/doa/mq/ExportRequestsListener.java, src/main/java/no/uio/ifi/localega/doa/services/AAIService.java
Replace java-jwt with io.jsonwebtoken.
=> Io jsonwebtoken replacement

.github/workflows/test.yml, pom.xml
Jcenter is now deprecated. This PR replaces 2 dependencies (crypth4gh and clearinghouse) which used to be hosted there with their new location, github.
It also only uses the lowest available versions released on github as a test to see if the new updates to dependabot catches these.
=> Replace jcenter packages

.github/workflows/publish.yml, Dockerfile
Adaptation to changes made in #180
=> Fix publish action

.github/workflows/publish.yml
=> change the credential for s4u in publish.yml

Dockerfile
Moved to eclipse-temurin instead of openJDK
=> Dockerfile - updating 

.github/workflows/build-and-scan-PR-container.yml, .github/workflows/ghcr-actions.yml, Dockerfile
Build and publish a container for each PR in order to simplify testing in a proper environment.
A cronjob is used to delete old containers.
=> Build container on pr

.github/workflows/build-and-scan-PR-container.yml
=> -add crypt4gh server to settings.xml in build-and-scan-PR-container.yml

pom.xml
=> resolve vuln #53 by upgrading snakeyaml explicitly

pom.xml, src/test/java/no/uio/ifi/localega/doa/LocalEGADOAApplicationTests.java
=> upgrade konghq dependency to fix security issue #64

pom.xml, src/main/java/no/uio/ifi/localega/doa/LocalEGADOAApplication.java, src/main/java/no/uio/ifi/localega/doa/services/StreamingService.java
=> upgrade io.minio dependency

src/main/java/no/uio/ifi/localega/doa/services/StreamingService.java
=> replace deprecated method in StringUtils isEmpty with hasLength

.github/workflows/test.yml, pom.xml
=> Upgrade java version

pom.xml
=> upgrade clearinghouse version

pom.xml, src/test/java/no/uio/ifi/localega/doa/LocalEGADOAApplicationTests.java
=> migrate from junit 4 to 5

pom.xml
=> upgrade minio to fix security issues #92 and #93

.env, hooks/build
=> -remove hook dir and .env file that are old outdated and unused onward.

pom.xml
=> Update minio version

docker-compose-posix-outbox.yml, docker-compose-s3-outbox.yml, src/test/java/no/uio/ifi/localega/doa/LocalEGADOAApplicationTests.java, test/mock_auth.py
=> add tests for dataset reference

src/test/java/no/uio/ifi/localega/doa/LocalEGADOAApplicationTests.java, test/mock_auth.py
=> add tests for visa token
